# automatic build to the gh-pages branch
# don't touch this
language: node_js
node_js:
  - "10"
cache: npm
before_script:
  - npm install
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  fqdn: hifumi.io
  on:
    branch: master
after_success:
  - wget https://raw.githubusercontent.com/Xetera/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/Xetera/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
