# automatic build to the gh-pages branch
language: node_js
cache: npm
before_script:
  - npm install
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: master
