[build]
  command = "npm run build"
  publish = "public/"

[context.production]
  publish = "public/"

[[headers]]
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin"
    # only load from specified domains
    Content-Security-Policy = "default-src 'self' https://whamer.000webhostapp.com; style-src https://*.fontawesome.com https://unpkg.com"
